language: node_js
os:
  - linux
node_js:
  - "8"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm i --silent
  - npm run lint
  - npm test
  - npm run export
  - npm run preview
